### ISSUE TITLE
Can't proccess caching manager on Flutter Web

### ISSUE THREAD

**Issue by chandrabezzo** [growthbook/growthbook-flutter#17]
Error Log:
packages/growthbook_sdk_flutter/src/Cache/caching_manager.dart 70:48         get localPath
packages/growthbook_sdk_flutter/src/Cache/caching_manager.dart 55:32         getTargetFile
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/growthbook_sdk_flutter/src/Cache/caching_manager.dart 54:31         getTargetFile
packages/growthbook_sdk_flutter/src/Cache/caching_manager.dart 38:36         saveContent
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
packages/growthbook_sdk_flutter/src/Cache/caching_manager.dart 34:27         saveContent
packages/growthbook_sdk_flutter/src/Cache/caching_manager.dart 30:5          putData
packages/growthbook_sdk_flutter/src/Features/features_view_model.dart 200:5  cacheFeatures
packages/growthbook_sdk_flutter/src/Features/features_view_model.dart 54:11  <fn>
packages/growthbook_sdk_flutter/src/Features/feature_data_source.dart 43:36  <fn>
packages/growthbook_sdk_flutter/src/Network/network.dart 100:7               consumeGetRequest
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>

**Comment by vazarkevych** [comment]
Hi, @chandrabezzo . We are closing the issue after checking and testing new functionality on Web [](https://github.com/growthbook/growthbook-flutter/pull/16)
