### ISSUE TITLE
Flutter Web Support?

### ISSUE THREAD

**Issue by chillbrodev** [growthbook/growthbook-flutter#20]
Hello, 

I was wondering if Flutter Web is supported. I did not see it on the Readme under the Support section. If it is supported could it be added to the Support section? If Flutter Web is not supported, will there be support?

Thanks

**Comment by frankylee** [comment]
Following and painfully awaiting a response to this. 😅

**Comment by vazarkevych** [comment]
Hi, @chillbrodev. Yes, Flutter Web is supported in the GrowthBook Flutter SDK. We will add it to the Support section. Have you tried using it on Flutter Web?

**Comment by chillbrodev** [comment]
> Hi, @chillbrodev. Yes, Flutter Web is supported in the GrowthBook Flutter SDK. We will add it to the Support section. Have you tried using it on Flutter Web?

Hey @vazarkevych , I have not tried it since the newer versions were released. We are using an older version at 3.0.0. I'll try the newer version and get back to you. I'll go ahead and close this issue. Thanks for your reply
