### ISSUE TITLE
Error when trying to get value out of feature flag used in experiment

### ISSUE THREAD

**Issue by cottonman132** [growthbook/growthbook-flutter#21]
Trying to get the value out of a feature flag that has a running experiment causes the following error:

```
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ExperimentEvaluator.evaluateExperiment (package:growthbook_sdk_flutter/src/Evaluator/experiment_evaluator.dart:88:59)
#1      FeatureEvaluator.evaluateFeature (package:growthbook_sdk_flutter/src/Evaluator/feature_evaluator.dart:214:18)
#2      GrowthBookSDK.feature (package:growthbook_sdk_flutter/src/growth_book_sdk.dart:191:7)
```

I assume it is caused by the fact that experiments using feature flags have no fallback attribute

**Comment by vazarkevych** [comment]
Hi, @cottonman132. Thank you for providing detailed information. We will check that and get back to you.

**Comment by stwonary** [comment]
we’re having the same issue. any updates on this?

**Comment by vazarkevych** [comment]
Hi, @stwonary. We now checking this issue. I will write you asap.

**Comment by vazarkevych** [comment]
Hi, @stwonary. Thank you for providing us with detailed information about the issue. We have also reproduced it and implemented a solution, which will be available in the next release.

**Comment by vazarkevych** [comment]
Hi, @stwonary. Here is a link to [pull request](https://github.com/growthbook/growthbook-flutter/pull/24) with fix.

**Comment by stwonary** [comment]
hi @vazarkevych  

i can confirm its working now. 
thank you.
