### ISSUE TITLE
Error being thrown when initializing growthbook

### ISSUE THREAD

**Issue by BennyKirschner** [growthbook/growthbook-flutter#22]
When trying to initialize GB, the following error is being thrown:

FormatException: SyntaxError: Unexpected token 'e', "en" is not valid JSON

The code itself didn't change, and a few months ago it was still working as expected. I updated my dependencies and now that I need it to run more tests, it doesn't work anymore because of this issue.

**Comment by BennyKirschner** [comment]
Downgrading to my previous version  growthbook_sdk_flutter: 2.1.0+0 seems to work.

**Comment by vazarkevych** [comment]
Hi, @BennyKirschner. So, you’re experiencing this issue only with the latest SDK version? We will check that and get back to you.

**Comment by BennyKirschner** [comment]
Either the latest or any version inbetween. I didn't have any tests running in about a year, so I didn't update the dependency in a while.

**Comment by vazarkevych** [comment]
Hi, @BennyKirschner. Can you please share the code how you initialize SDK?

**Comment by BennyKirschner** [comment]
`gb = await GBSDKBuilderApp(
      attributes: {'id': growthBookId},
      enable: !FeatureFlags.isAnyOverwolfBuild,
      hostURL: 'https://cdn.growthbook.io/',
      apiKey: "sdk-3uuaGOkJjeNt1JF0",
      growthBookTrackingCallBack: (experiment, result) => logEvent(
        LogEvent.EXPERIMENT_VIEWED,
        parameters: {
          'experimentId': experiment.key ?? '',
          'variationId': result.variationID ?? '',
        },
      ),
    ).initialize();`
    
    Like this

**Comment by vazarkevych** [comment]
HI, @BennyKirschner. Do you have time to check that?
