### ISSUE TITLE
Hashing doesn't work on Flutter Web

### ISSUE THREAD

**Issue by kobreu** [growthbook/growthbook-flutter#23]
Hi,

I noticed that the FNV Hashing doesn't work on Flutter web. The problem is in this line of gb_utils.dart:

```dart
final int mod32 = 1 << 32; // Equivalent to 2^32
``` 

on web this evaluates to 0 as on web shift operators operate on 32-bit integers (see here: https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin)

The fix would be to change the line to

```dart
final int mod32 = 0x100000000; // Equivalent to 2^32
``` 

Best regards,

Korbinian

**Comment by vazarkevych** [comment]
Hi, @kobreu. Thank you for mentioning that. You're right, we will add this change to our next release.

**Comment by kobreu** [comment]
Great, thanks!
